---
# SpdxModel Library Requirements
#
# This file is the root requirements file that includes all subsystem requirements.
# Requirements are split into separate files under docs/reqstream/ mirroring the source structure.

includes:
  - docs/reqstream/spdx-model/spdx-model.yaml
  - docs/reqstream/spdx-model/platform-requirements.yaml
  - docs/reqstream/spdx-model/io/io.yaml
  - docs/reqstream/spdx-model/io/spdx-2-json-deserializer.yaml
  - docs/reqstream/spdx-model/io/spdx-2-json-serializer.yaml
  - docs/reqstream/spdx-model/transform/transform.yaml
  - docs/reqstream/spdx-model/transform/spdx-relationships.yaml
  - docs/reqstream/spdx-model/spdx-annotation.yaml
  - docs/reqstream/spdx-model/spdx-checksum.yaml
  - docs/reqstream/spdx-model/spdx-creation-information.yaml
  - docs/reqstream/spdx-model/spdx-external-document-reference.yaml
  - docs/reqstream/spdx-model/spdx-external-reference.yaml
  - docs/reqstream/spdx-model/spdx-extracted-licensing-info.yaml
  - docs/reqstream/spdx-model/spdx-file.yaml
  - docs/reqstream/spdx-model/spdx-package.yaml
  - docs/reqstream/spdx-model/spdx-package-verification-code.yaml
  - docs/reqstream/spdx-model/spdx-relationship.yaml
  - docs/reqstream/spdx-model/spdx-snippet.yaml
  - docs/reqstream/ots/ots.yaml
