---
# SpdxModel Library Requirements
#
# This file is the root requirements file that includes all subsystem requirements.
# Requirements are split into separate files under docs/reqstream/ mirroring the source structure.

includes:
  - docs/reqstream/io/io.yaml
  - docs/reqstream/system.yaml
  - docs/reqstream/platform-requirements.yaml
  - docs/reqstream/transform/transform.yaml
  - docs/reqstream/ots/ots.yaml
  - docs/reqstream/spdx-annotation.yaml
  - docs/reqstream/spdx-checksum.yaml
  - docs/reqstream/spdx-creation-information.yaml
  - docs/reqstream/spdx-external-document-reference.yaml
  - docs/reqstream/spdx-external-reference.yaml
  - docs/reqstream/spdx-extracted-licensing-info.yaml
  - docs/reqstream/spdx-file.yaml
  - docs/reqstream/spdx-package.yaml
  - docs/reqstream/spdx-package-verification-code.yaml
  - docs/reqstream/spdx-relationship.yaml
  - docs/reqstream/spdx-snippet.yaml
