name: 🐛 Bug Report
description: Report a bug or issue with SpdxModel
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue.
      placeholder: |
        1. Create a new SpdxDocument with...
        2. Call method X with parameters...
        3. See error...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue.
      placeholder: |
        ```csharp
        // Your code here
        ```
      render: csharp

  - type: input
    id: version
    attributes:
      label: SpdxModel Version
      description: What version of SpdxModel are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      options:
        - .NET 8
        - .NET 9
        - .NET 10
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any other relevant environment details (IDE, runtime, etc.)
      placeholder: |
        - IDE: Visual Studio 2022
        - Runtime: Self-contained deployment
        - etc.

  - type: textarea
    id: logs
    attributes:
      label: Error Messages or Logs
      description: If applicable, provide any error messages, stack traces, or logs.
      placeholder: Paste error messages or logs here...
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I am using the latest version of SpdxModel
          required: false
        - label: I have provided all the information requested above
          required: true
