---
name: ✨ Feature Request
description: Suggest a new feature or enhancement for SpdxModel
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your
        request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation this feature would solve.
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific API designs, usage examples, or implementation ideas.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches have you thought about?

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: If applicable, provide an example of how you would use this feature.
      placeholder: |
        ```csharp
        // Example of how you envision using the feature
        ```
      render: csharp

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category best describes this feature?
      options:
        - API Enhancement
        - New API
        - Performance Improvement
        - Documentation
        - Developer Experience
        - SPDX Specification Support
        - Serialization/Deserialization
        - Validation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my use case
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: |
        Help us understand how you plan to use this feature in your project.
        What are you trying to accomplish?
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved performance
        - Better developer experience
        - Support for new SPDX specification features
        - etc.

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute
      description: Are you willing to help implement this feature?
      options:
        - "Yes, I can submit a pull request"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "No, but I can provide feedback"
        - "No, I just want to suggest the idea"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, links, or references about the feature request here.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature aligns with the goals and scope of the SpdxModel project
          required: true
        - label: I have provided all the information requested above
          required: true
