name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (1.0.0)'
        required: true

jobs:
  release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet 6/8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x

    - name: Restore Tools
      run: >
        dotnet tool restore
      
    - name: Restore Dependencies
      run: >
        dotnet restore
      
    - name: Build
      run: >
        dotnet build
        --no-restore
        --configuration Release
        --property:Version=${{ github.event.inputs.version }}

    - name: Test
      run: >
        dotnet test
        --no-build
        --configuration Release
        --property:Version=${{ github.event.inputs.version }}

    - name: Generate SBOM
      run: >
        dotnet sbom-tool generate
        -b src/DemaConsulting.SpdxModel/bin/Release
        -bc src/DemaConsulting.SpdxModel
        -pn DemaConsulting.SpdxModel
        -pv ${{ github.event.inputs.version }}
        -ps DemaConsulting
        -nsb https://DemaConsulting.com/SpdxModels

    - name: Generate Tests SBOM
      run: >
        dotnet sbom-tool generate
        -b test/DemaConsulting.SpdxModel.Tests/bin/Release
        -bc test/DemaConsulting.SpdxModel.Tests
        -cd "--DirectoryExclusionList **/Examples/**"
        -pn DemaConsulting.SpdxModel.Tests
        -pv ${{ github.event.inputs.version }}
        -ps DemaConsulting
        -nsb https://DemaConsulting.com/SpdxModels.Tests

    - name: Run SBOM Workflow
      run: >
        dotnet spdx-tool
        run-workflow spdx-workflow.yaml

    - name: Create Dotnet Tool
      run: >
        dotnet pack
        --no-build
        --no-restore
        --property:PackageVersion=${{ github.event.inputs.version }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '**/*.nupkg,**/manifest.spdx.json,**/manifest.spdx.json.sha256,*summary.md'
        generateReleaseNotes: true
        tag: ${{ github.event.inputs.version }}

    - name: Publish to Nuget
      run: >
        dotnet
        nuget push
        src/DemaConsulting.SpdxModel/bin/Release/*.nupkg
        --source "https://api.nuget.org/v3/index.json"
        --api-key "${{ secrets.DEMACONSULTINGNUGETKEY }}"
